export const dataConstants = {

  SPEED_REQUEST: 'DATA_SPEED_REQUET',
  SPEED_SUCCESS: 'DATA_SPEED_SUCCESS',
  SPEED_FAILURE: 'DATA_SPEED_FAILURE',

  ODO_REQUEST: 'DATA_ODO_REQUET',
  ODO_SUCCESS: 'DATA_ODO_SUCCESS',
  ODO_FAILURE: 'DATA_ODO_FAILURE',

  TEMP_REQUEST: 'DATA_TEMP_REQUET',
  TEMP_SUCCESS: 'DATA_TEMP_SUCCESS',
  TEMP_FAILURE: 'DATA_TEMP_FAILURE',

}
